# Generated by Django 4.1.2 on 2022-12-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power655', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power655',
            options={'ordering': ['-id']},
        ),
    ]
