# Generated by Django 4.1.3 on 2022-12-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mega645',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jackpot', models.CharField(max_length=30)),
                ('ngayQuay', models.CharField(max_length=30)),
                ('so1', models.CharField(max_length=2)),
                ('so2', models.CharField(max_length=2)),
                ('so3', models.CharField(max_length=2)),
                ('so4', models.CharField(max_length=2)),
                ('so5', models.CharField(max_length=2)),
                ('so6', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
