# Generated by Django 4.1.3 on 2022-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Max3DPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayQuay', models.CharField(max_length=20)),
                ('giaiDacBiet1', models.IntegerField()),
                ('giaiDacBiet2', models.IntegerField()),
                ('giaiNhat1', models.IntegerField()),
                ('giaiNhat2', models.IntegerField()),
                ('giaiNhat3', models.IntegerField()),
                ('giaiNhat4', models.IntegerField()),
                ('giaiNhi1', models.IntegerField()),
                ('giaiNhi2', models.IntegerField()),
                ('giaiNhi3', models.IntegerField()),
                ('giaiNhi4', models.IntegerField()),
                ('giaiNhi5', models.IntegerField()),
                ('giaiNhi6', models.IntegerField()),
                ('giaiNhi7', models.IntegerField()),
                ('giaiNhi8', models.IntegerField()),
                ('giaiBa1', models.IntegerField()),
                ('giaiBa2', models.IntegerField()),
                ('giaiBa3', models.IntegerField()),
                ('giaiBa4', models.IntegerField()),
                ('giaiBa5', models.IntegerField()),
                ('giaiBa6', models.IntegerField()),
                ('giaiBa7', models.IntegerField()),
                ('giaiBa8', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
