# Generated by Django 4.1.3 on 2022-12-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max3d', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='max3d',
            old_name='giaiDacbiet1',
            new_name='giaiDacBiet1',
        ),
        migrations.RenameField(
            model_name='max3d',
            old_name='giaiDacbiet2',
            new_name='giaiDacBiet2',
        ),
    ]
