# Generated by Django 4.1.2 on 2022-12-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('max3d', '0002_rename_giaidacbiet1_max3d_giaidacbiet1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='max3d',
            options={'ordering': ['-id']},
        ),
    ]
